version: '3'
services:
  mysql:
    build: ./mysql
    image: 'cmyanko/mysql:5.7'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - '~/.mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: example

  ssc:
    image: 'cmyanko/ssc:18.10'
    build: ./ssc-master
    depends_on:
      - mysql
    ports:
      - '8888:8080'
    volumes:
      - '~/.fortify_home:/usr/local/tomcat/fortify'

  iq-server:
    image: 'cmyanko/my-iq-server:1.62.0'
    build: ./iq-server
    volumes:
      - '~/iq-data:/sonatype-work'
      - '~/iq-logs:/opt/sonatype/nexus-iq-server/log'
    ports:
      - '8070:8070'
      - '8071:8071'

  intSvc:
    build: ./intSvc
    depends_on:
      - ssc
      - iq-server
    ports:
      - '8182:8182'
    volumes:
      - '~/.intSvcWorkFolder:/home/nexus/.work'
    image: 'cmyanko/nexus-ssc-integration:18.0.4'

  nginx-proxy:
    build: ./nginx
    image: 'cmyanko/sonatype_nginx-proxy:2.4'
    ports:
      - '443:443'
      - '5000:5000'
      - '8011:8011'
      - '18443:18443'
    command:
      - nginx
      - '-g'
      - daemon off;

  nexus:
    image: 'cmyanko/nexus3:3.15.2'
    build: ./nexus
    volumes:
      - '~/nexus-data:/nexus-data'
    ports:
      - '8081:8081'

# Moved to a local install to take advantage of the SSL in nginx fo docker work
# left in as a reference
  # jenkins:
  #   image: jenkinsci/blueocean
  #   user: root
  #   volumes:
  #     - '~/.jenkins:/var/jenkins_home'
  #     - '/var/run/docker.sock:/var/run/docker.sock'
  #   ports:
  #     - '8080:8080'
  #     - '50000:50000'

  anchore-engine:
    image: docker.io/anchore/anchore-engine:latest
    #privileged: true
    depends_on:
     - anchore-db
    ports:
     - "8228:8228"
     - "8338:8338"
    volumes:
     - ~/.aevolume/config:/config/:z
    logging:
     driver: "json-file"
     options:
      max-size: 100m
    environment:
     # NOTE: this should be set to the same name as this service (e.g. anchore-engine)
     - ANCHORE_HOST_ID=dockerhostid-anchore-engine
     - ANCHORE_ENDPOINT_HOSTNAME=anchore-engine
  anchore-db:
    image: "postgres:9"
    volumes:
     - ~/.aevolume/db:/var/lib/postgresql/data/pgdata/:z
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata/
    logging:
     driver: "json-file"
     options:
      max-size: 100m
    #uncomment to expose a port to allow direct/external access to the DB, for debugging
    #ports:
    # - "2345:5432"
  # victoria:
  #   image: 'victoria:1.0.0-44'
  #   build: ./victoria
  #   volumes:
  #     - '~/.victoria/db:/home/nexus/db'
  #     - '~/.victoria/log:/home/nexus/log'
  #     - '~/.victoria/tmp:/home/nexus/tmp'
  #   ports:
  #     - '8090:8090'
  #     - '8091:8091'
  #   depends_on:
  #     - iq-server
